import { Student } from './types';

export const STUDENTS: Student[] = [
    { id: 's1', name: 'ABDUL ARSHAD M', avatarUrl: 'https://picsum.photos/seed/s1/100/100', notes: '' },
    { id: 's2', name: 'ALIF RAFIATHUL FAHMITHA K', avatarUrl: 'https://picsum.photos/seed/s2/100/100', notes: '' },
    { id: 's3', name: 'ANITHA A', avatarUrl: 'https://picsum.photos/seed/s3/100/100', notes: '' },
    { id: 's4', name: 'ASHWIN K', avatarUrl: 'https://picsum.photos/seed/s4/100/100', notes: '' },
    { id: 's5', name: 'ASWATHI THOMAS', avatarUrl: 'https://picsum.photos/seed/s5/100/100', notes: '' },
    { id: 's6', name: 'CATHARIN SAMANTHA S J', avatarUrl: 'https://picsum.photos/seed/s6/100/100', notes: '' },
    { id: 's7', name: 'DIVYA R', avatarUrl: 'https://picsum.photos/seed/s7/100/100', notes: '' },
    { id: 's8', name: 'EVA SAFRENA H', avatarUrl: 'https://picsum.photos/seed/s8/100/100', notes: '' },
    { id: 's9', name: 'GAYAPRAVISHVARAN S', avatarUrl: 'https://picsum.photos/seed/s9/100/100', notes: '' },
    { id: 's10', name: 'GAYATHIRI MEENA P', avatarUrl: 'https://picsum.photos/seed/s10/100/100', notes: '' },
    { id: 's11', name: 'HARI HARAN K', avatarUrl: 'https://picsum.photos/seed/s11/100/100', notes: '' },
    { id: 's12', name: 'HARIS JERAALD WILLSON S', avatarUrl: 'https://picsum.photos/seed/s12/100/100', notes: '' },
    { id: 's13', name: 'HEMAVARSHINI P', avatarUrl: 'https://picsum.photos/seed/s13/100/100', notes: '' },
    { id: 's14', name: 'JACQUES JANIEL V', avatarUrl: 'https://picsum.photos/seed/s14/100/100', notes: '' },
    { id: 's15', name: 'JAGADESHWAR K', avatarUrl: 'https://picsum.photos/seed/s15/100/100', notes: '' },
    { id: 's16', name: 'JOICE PRAVEENA G', avatarUrl: 'https://picsum.photos/seed/s16/100/100', notes: '' },
    { id: 's17', name: 'KAVYA C', avatarUrl: 'https://picsum.photos/seed/s17/100/100', notes: '' },
    { id: 's18', name: 'KISHORE KUMAR J', avatarUrl: 'https://picsum.photos/seed/s18/100/100', notes: '' },
    { id: 's19', name: 'MAARKASAMRAKSHANI S', avatarUrl: 'https://picsum.photos/seed/s19/100/100', notes: '' },
    { id: 's20', name: 'MOHAMMED SADDICK S', avatarUrl: 'https://picsum.photos/seed/s20/100/100', notes: '' },
    { id: 's21', name: 'NANDHINI K', avatarUrl: 'https://picsum.photos/seed/s21/100/100', notes: '' },
    { id: 's22', name: 'POOJA M', avatarUrl: 'https://picsum.photos/seed/s22/100/100', notes: '' },
    { id: 's23', name: 'PRABAVATHI P', avatarUrl: 'https://picsum.photos/seed/s23/100/100', notes: '' },
    { id: 's24', name: 'ROSHINI K', avatarUrl: 'https://picsum.photos/seed/s24/100/100', notes: '' },
    { id: 's25', name: 'RUBBINI B', avatarUrl: 'https://picsum.photos/seed/s25/100/100', notes: '' },
    { id: 's26', name: 'SHIVANI A', avatarUrl: 'https://picsum.photos/seed/s26/100/100', notes: '' },
    { id: 's27', name: 'SHIVANI L', avatarUrl: 'https://picsum.photos/seed/s27/100/100', notes: '' },
    { id: 's28', name: 'SHWETHA S', avatarUrl: 'https://picsum.photos/seed/s28/100/100', notes: '' },
    { id: 's29', name: 'SOPHIAA EVANGELINE L', avatarUrl: 'https://picsum.photos/seed/s29/100/100', notes: '' },
    { id: 's30', name: 'SRINIVASAN H', avatarUrl: 'https://picsum.photos/seed/s30/100/100', notes: '' },
    { id: 's31', name: 'SWATHY S', avatarUrl: 'https://picsum.photos/seed/s31/100/100', notes: '' },
    { id: 's32', name: 'THAMEEMUN ANSARI M', avatarUrl: 'https://picsum.photos/seed/s32/100/100', notes: '' },
    { id: 's33', name: 'VENU ARAVIND B', avatarUrl: 'https://picsum.photos/seed/s33/100/100', notes: '' },
    { id: 's34', name: 'VIJAYKARTHIKRAJA V', avatarUrl: 'https://picsum.photos/seed/s34/100/100', notes: '' },
    { id: 's35', name: 'VISHWA DHARSHINI M', avatarUrl: 'https://picsum.photos/seed/s35/100/100', notes: '' },
    { id: 's38', name: 'SOZAN RUNGSUNG R', avatarUrl: 'https://picsum.photos/seed/s38/100/100', notes: '' },
    { id: 's41', name: 'SANJAY B', avatarUrl: 'https://picsum.photos/seed/s41/100/100', notes: '' },
    { id: 's42', name: 'REANNE FEWKES R', avatarUrl: 'https://picsum.photos/seed/s42/100/100', notes: '' },
    { id: 's43', name: 'MONISHA V', avatarUrl: 'https://picsum.photos/seed/s43/100/100', notes: '' },
    { id: 's44', name: 'KARISHNI PV', avatarUrl: 'https://picsum.photos/seed/s44/100/100', notes: '' },
    { id: 's45', name: 'RIYAJ AHMAD', avatarUrl: 'https://picsum.photos/seed/s45/100/100', notes: '' },
  ];